### ISSUE TITLE
<Root> was created without expected prop 'form'

### ISSUE THREAD

**Issue by selfagency** [themesberg/flowbite-svelte-blocks#25] opened 2023-08-02 14:27 UTC
When I try to use the login form component, I get the following error:

<Root> was created without expected prop 'form'

**Comment by shinokada** [comment] 2023-08-26 06:52
I'm not able to reproduce the error.
I close the issue for now.
Please give me more details in the future issue.

**Closed by shinokada** 2023-08-26 06:52 UTC
